### ISSUE TITLE
Increase pen MAX_X/MAX_Y resolution

### ISSUE THREAD

**Issue by cfalas** [games-on-whales/inputtino#12]
When working on higher resolution displays, pen accuracy is still limited to 1920x1080, which may lead to not-very-smooth lines.

Increasing MAX_X and MAX_Y in the code should fix this https://github.com/games-on-whales/inputtino/blame/stable/src/uinput/pentablet.cpp#L24-L25.

However, I'm not sure what a reasonable value for that is - some devices support subpixel precision, much higher than the resolution of their display. I don't think there's any disadvantage of setting this to a very large value, so perhaps we could just go for 65536x65536 or something like that?

Example of 65536x65536 instead of 1920x1080:
![image](https://github.com/user-attachments/assets/d0dbcd13-38c4-4e45-a246-7b416c7942f2)

**Comment by cfalas** [comment]
If I understand the Android docs correctly, my tablet's digitizer has a [fuzz](https://developer.android.com/reference/kotlin/android/view/InputDevice.MotionRange#getFuzz()) of 0.3769x0.3769 pixels, with a `range` of 2960x1820 (which is the display resolution), which gives a resolution of ~7854x4830. 

Let me know what you think a good value for the max is. Perhaps 19200x10800 might be good so that it matches the [mouse config](https://github.com/games-on-whales/inputtino/blob/stable/src/uinput/mouse.cpp#L22-L23) (and still looks smooth on my tablet)?

**Comment by ABeltramo** [comment]
I can't remember where originally I took those values, from a quick scan of the Wacom driver on the Linux kernel I couldn't find anything (I think that's where I was basing my assumptions).  
I can't see anything wrong with changing it, the difference in the screenshot above is night and day, so I'd be happy to take a bigger default value.
